### ISSUE TITLE
Calibrator check not correct.

### ISSUE THREAD

**Issue by PeterKamphuis** [caracal-pipeline/caracal#1115]
After my flagging woes I get the nice error:

```
2020-05-18 13:36:15 CARACal ERROR: The flux calibrator field "3C286" could not be found in our database or in the CASA NRAO database [RuntimeError]
```
However, this has never before been an issue and clearly 3C286 is part of the casa flux calibrator database. See here:

https://casa.nrao.edu/casadocs/casa-5.1.0/reference-material/flux-calibrator-models

So the check on the casa database is not correct somehow.

**Comment by KshitijT** [comment]
What's the field name specified as in the MS?

**Comment by PeterKamphuis** [comment]
@KshitijT 3C286

**Comment by KshitijT** [comment]
Could you post your crosscal settings?

**Comment by PeterKamphuis** [comment]
```
crosscal:
  enable: true
  uvrange: '>1klambda'
  label_in: 'cal'
  set_model:
    enable: true
  primary:
    reuse_existing_gains: true
    order: GBAGB
    combine: [ "", "", null, "",""]
    solint: ['inf', 'inf,3ch', null, 'inf', 'inf']
    calmode: [p, ap, null, ap, ap] 
    b_fillgaps: 70
    plotgains: true
  secondary:
    reuse_existing_gains: False
    order: GBAGB
    apply: B
    combine: ["","", null,"",""]
    solint: ['32s', "inf,3ch",null,"32s","inf,3ch"]
    calmode: [ap,ap,null,ap,ap]
    plotgains: True
  apply_cal: 
    applyto: 
      - gcal
      - bpcal
```

**Comment by PeterKamphuis** [comment]
@KshitijT Please note that this is a set without intents and the calibrators are set explicitly in the yml file.

```
obsconf:
  refant: '10'
  target: ['2014AD']
  fcal: ['3C147']
  bpcal: ['3C147']
  gcal: ['1130-148']
```
Testing 3C147 at the moment but it was exactly the same for 3C286.
