### ISSUE TITLE
Phase vs frequency plots look very inconsistent between ragavi and shadems

### ISSUE THREAD

**Issue by molnard89** [caracal-pipeline/caracal#1159]
When I plot phase vs channel of the same dataset, using the same column, I get very different looking figures between ragavi and shadems. I'll put the relevant config file snippet below for both with figures attached:

```
inspect__2:
  enable: true
  label_in: 'cal'
  field: 'calibrators'
  label_plot: 'primary_only'
  dirname: crosscalPO
  standard_plotter: none
  shadems:
    enable: true
    ignore_errors: true
    default_column: CORRECTED_DATA
    plots_by_field:
      - "-x FREQ   -y phase -c ANTENNA1 --corr XX --cnum 64 --field 1"
      - "-x FREQ   -y phase -c ANTENNA1 --corr YY --cnum 64 --field 1"
```

And the resulting shadems plots:

![first-centSplit32k-primary_only-bpcal-J0408-6545-CORRECTED_DATA-XX-phase-FREQ-ANTENNA1](https://user-images.githubusercontent.com/43236491/83679617-0007f400-a5e0-11ea-87db-c5152d4c5384.png)

![first-centSplit32k-primary_only-bpcal-J0408-6545-CORRECTED_DATA-YY-phase-FREQ-ANTENNA1](https://user-images.githubusercontent.com/43236491/83679623-04341180-a5e0-11ea-86b9-b560cbc938c5.png)

Now the ragavi version:

```
inspect__3:
  enable: true
  label_in: 'cal'
  field: 'calibrators'
  label_plot: 'primary_only'
  dirname: crosscalPO
  phase_chan:
    enable: true
    avgtime: '60'
```

And the resulting plots:

<img width="1440" alt="ragavi_phase_chan_YY" src="https://user-images.githubusercontent.com/43236491/83679979-93412980-a5e0-11ea-8b4d-8d72c7f43fbc.png">

<img width="1432" alt="ragavi_phase_chan_XX" src="https://user-images.githubusercontent.com/43236491/83679993-976d4700-a5e0-11ea-8984-89fb24f3819b.png">

-400 to 400 degrees in phase in itself looks wild, so in combination with the shadems plot, we think this is likely some plotting issue, not data related. Any ideas what might be going on?
