### ISSUE TITLE
Sorting schema string snag

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1219]
The `de_sources_manual` parameter in ddcal worker is defined in the schema as:

```
         de_sources_manual:
           seq:
             - type: str
           desc: List of sources per target to tag for DD calibration, in the same order as the 'de_target_manual' list. Use ';' to separate different sources per target.
           required: false
           example: ''
```

It took the list of sources in the format ['RA1,DEC1,SIZE1'; 'RA2, DEC2,SIZE2';......], a list of strings with 1st element 'RA1,DEC1,SIZE1' and so on; everything was fine in the paradise. Recently, however, CARACal has started the format to mean  a list formed of elements 'RA1', 'RA2', 'SIZE1', 'RA2'.... , which plays havoc with the ddcal worker code. If I use ";" instead of "," it does take it as a single source, but remember that ";" is already use to separate different sources, so that's a dead end.

@o-smirnov said he might have some clues as to why this is happening.
