### ISSUE TITLE
Et tu, ShadeMS??

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1253]
Reeling from Ragavi's treachery, I turned to ShadeMS for help, but apparently the pipeline must die.

Alright, this is probably my lack of knowledge about this bleeding-edge software; ignorance is (sadly) not bliss this time.

I get the following errors:
```
# 2020-10-05 20:52:01: Running shadems /stimela_mount/msdir/X-avg-cal.ms -x UV -y amp -c SCAN_NUMBER --png X-avg-cal-1gc-gcal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}.png --title '{ms} gcal{_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col CORRECTED_DATA --corr XX,YY --field  --iter-field
# usage: shadems [-h] [-v] [-x XAXIS] [-y YAXIS] [-a AAXIS] [--ared ARED]
#                [-c COLOUR_BY] [-C COLUMN] [--noflags] [--noconj] [--xmin XMIN]
#                [--xmax XMAX] [--ymin YMIN] [--ymax YMAX] [--cmin CMIN]
#                [--cmax CMAX] [--cnum CNUM] [--iter-field] [--iter-antenna]
#                [--iter-spw] [--iter-scan] [--iter-corr] [--iter-ant]
#                [--ant ANT] [--ant-num ANT_NUM] [--baseline BASELINE]
#                [--spw SPW] [--field FIELD] [--scan SCAN] [--corr CORR]
#                [--chan CHAN] [-X XCANVAS] [-Y YCANVAS]
#                [--norm {auto,eq_hist,cbrt,log,linear}] [--cmap CMAP]
#                [--bmap BMAP] [--dmap DMAP] [--spread-pix PIX]
#                [--spread-thr THR] [--bgcol BGCOL] [--fontsize FONTSIZE]
#                [--dir DIR] [-s SUFFIX] [--png PNGNAME] [--title TITLE]
#                [--xlabel XLABEL] [--ylabel YLABEL] [-d] [-z NROWS] [-j N]
#                [--profile]
#                ms
# shadems: error: argument --field: expected one argument
# 2020-10-05 20:52:07: shadems exited with code 2
# 2020-10-05 20:52:07: Running shadems /stimela_mount/msdir/X-avg-cal.ms -x UV -y amp -c ANTENNA1 --cnum 64 --png X-avg-cal-1gc-gcal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}.png --title '{ms} gcal{_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col CORRECTED_DATA --corr XX,YY --field  --iter-field
# usage: shadems [-h] [-v] [-x XAXIS] [-y YAXIS] [-a AAXIS] [--ared ARED]
#                [-c COLOUR_BY] [-C COLUMN] [--noflags] [--noconj] [--xmin XMIN]
#                [--xmax XMAX] [--ymin YMIN] [--ymax YMAX] [--cmin CMIN]
#                [--cmax CMAX] [--cnum CNUM] [--iter-field] [--iter-antenna]
#                [--iter-spw] [--iter-scan] [--iter-corr] [--iter-ant]
#                [--ant ANT] [--ant-num ANT_NUM] [--baseline BASELINE]
#                [--spw SPW] [--field FIELD] [--scan SCAN] [--corr CORR]
#                [--chan CHAN] [-X XCANVAS] [-Y YCANVAS]
#                [--norm {auto,eq_hist,cbrt,log,linear}] [--cmap CMAP]
#                [--bmap BMAP] [--dmap DMAP] [--spread-pix PIX]
#                [--spread-thr THR] [--bgcol BGCOL] [--fontsize FONTSIZE]
#                [--dir DIR] [-s SUFFIX] [--png PNGNAME] [--title TITLE]
#                [--xlabel XLABEL] [--ylabel YLABEL] [-d] [-z NROWS] [-j N]
#                [--profile]
#                ms
# shadems: error: argument --field: expected one argument
# 2020-10-05 20:52:13: shadems exited with code 2
# 2020-10-05 20:52:13: Running shadems /stimela_mount/msdir/X-avg-cal.ms -x UV -y phase -c ANTENNA1 --cnum 64 --png X-avg-cal-1gc-gcal-{field}{_Spw}{_Scan}{_Ant}-{label}{_alphalabel}{_colorlabel}{_suffix}.png --title '{ms} gcal{_field}{_Spw}{_Scan}{_Ant}{_title}{_Alphatitle}{_Colortitle}' --col CORRECTED_DATA --corr XX,YY --field  --iter-field
# usage: shadems [-h] [-v] [-x XAXIS] [-y YAXIS] [-a AAXIS] [--ared ARED]
#                [-c COLOUR_BY] [-C COLUMN] [--noflags] [--noconj] [--xmin XMIN]
#                [--xmax XMAX] [--ymin YMIN] [--ymax YMAX] [--cmin CMIN]
#                [--cmax CMAX] [--cnum CNUM] [--iter-field] [--iter-antenna]
#                [--iter-spw] [--iter-scan] [--iter-corr] [--iter-ant]
#                [--ant ANT] [--ant-num ANT_NUM] [--baseline BASELINE]
#                [--spw SPW] [--field FIELD] [--scan SCAN] [--corr CORR]
#                [--chan CHAN] [-X XCANVAS] [-Y YCANVAS]
#                [--norm {auto,eq_hist,cbrt,log,linear}] [--cmap CMAP]
#                [--bmap BMAP] [--dmap DMAP] [--spread-pix PIX]
#                [--spread-thr THR] [--bgcol BGCOL] [--fontsize FONTSIZE]
#                [--dir DIR] [-s SUFFIX] [--png PNGNAME] [--title TITLE]
#                [--xlabel XLABEL] [--ylabel YLABEL] [-d] [-z NROWS] [-j N]
#                [--profile]
#                ms
# shadems: error: argument --field: expected one argument
# 2020-10-05 20:52:19: shadems exited with code 2
```

and so on..

The relevant settings in inspect data are (and these used to work, atleast for different datasets): 

```
inspect:
  enable: true
  label_in: 'cal'
  label_plot: '1gc'
  field: 'calibrators'
  shadems:
    enable: true
    default_column: CORRECTED_DATA
    plots_by_field:
      - "-x UV    -y amp    -c SCAN_NUMBER"
      - "-x UV    -y amp    -c ANTENNA1 --cnum 64"
      - "-x UV    -y phase  -c ANTENNA1 --cnum 64"
      - "-x FREQ  -y amp    -c SCAN_NUMBER"
      - "-x FREQ  -y amp    -c ANTENNA1 --cnum 64"
      - "-x U     -y V      -c amp"
      - "-x BASELINE -y FREQ -c amp"
    ignore_errors: true
  standard_plotter: shadems
  real_imag:
    enable: true
    avgtime: '60'
  amp_phase:
    enable: true
    avgtime: '60'
  amp_uvwave:
    enable: true
    avgtime: '60'
  amp_ant:
    enable: true
    avgtime: '60'
  phase_uvwave:
    enable: true
    avgtime: '60'
  amp_scan:
    enable: true
    avgtime: '60'
```

Any clues ?
