### ISSUE TITLE
inspect worker shadems section: allow listed args to override automatic args

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1257]
Currently,

```
inspect:
  correlation: all
  shadems:
    enable: true
    default_column: CORRECTED_DATA
    plots_by_field:
      - "-x real  -y imag   -c CORR --corr IQUV"
```

...plots XX/XY/YX/YY, because a ``--corr`` argument based on ``correlation: all`` is added to the end of the command line, so the manual ``--corr`` setting is overridden.

Swap the order around so that manual settings override automatic settings.
