### ISSUE TITLE
generate summary.json automatically as needed without user intervention

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1272]
See discussion in #1270.  

Since this is essentially an internal data product required for consistent operation, there's no point leaving its generation (or lack thereof) up to the user.

**Comment by Athanaseus** [comment]
resolved by #1271

Option:
```
          summary_json:
            desc: Run the MSUtils summary function to get observation information written as a JSON file, which can then be used to automatically configure pipeline. This is not executed if the JSON file already exists.
            type: bool
            required: false
            example: 'True'
```
