### ISSUE TITLE
More flexibility on the location of the input images/cubes when mosaicking

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1290]
When mosaicking, the input images and cubes must be located in (sub-directories of) `general:output/continuum` and `general:output/cubes`, respectively. This is not very flexible. As an example, I have all my cubes at:

```
/disc1/<ID>/output/cubes/<ID>.fits
```

where `ID` runs over the pointings of the mosaic (i.e., each pointing has its own data reduction directory). In this case, I cannot run the mosaic worker unless I copy all input cubes to (sub-directories of) a common directory, e.g., `/disc1/mosaic/output/cubes`.

I have solved this problem in the branch https://github.com/caracal-pipeline/caracal/tree/what-the-flag .

In that branch, input images and cubes must be more generally located in (subdirectories of) the CWD.

In the example above, I do not need to move any cubes. I can simply run caracal from `/disc1/` with the following settings in the CARACal config file`/disc1/caracal_settings.yml`:

```
mosaic:
  enable: true
  mosaic_type: spectral
  target_images:
    - id1/output/cubes/id1.fits
    - id2/output/cubes/id2.fits
    - id3/output/cubes/id3.fits
```

Note that the paths in `target_images` are relative to the CWD. (In current master they are relative to `general:output/continuum` or `general:output/cubes` depending on the mosaic type.)

Please let me know whether you have any comments on this implementation. Auto-selection of the images/cubes to be mosaicked is still working.

Pinging @svw26 @gigjozsa .
