### ISSUE TITLE
Improved plot specification for inspect: shadems section

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1291]
I have become prone to plotting everything, just because I can. Tthe overhead is tolerable, and having everything I can think of ready for scrunity during the almost inevitable post-mortem is proving very valuable. However, my ``inspect: shadems`` section is turning into an unreadable monster, e.g.:

```yml
    plots_by_field:
      - "-x BASELINE_M -y FREQ -c amp"
      - "-x real  -y imag -c SCAN_NUMBER --cnum 100"
      - "-x real  -y imag -c ANTENNA1 --cnum 100"
      - "-x real  -y imag -c CORR --corr IQUV --hline 0: --vline 0:"
      - "-x ANTENNA1 -y ANTENNA2 -c SCAN_NUMBER --cnum 100 --aaxis phase --ared std"
      - "-x ANTENNA1 -y ANTENNA2 -c SCAN_NUMBER --cnum 100 --aaxis amp --ared mean"
      - "-x UV    -y amp    -c SCAN_NUMBER --cnum 100"
      - "-x UV    -y amp    -c ANTENNA1 --cnum 64"
      - "-x UV    -y phase  -c ANTENNA1 --cnum 64"
      - "-x FREQ  -y amp    -c SCAN_NUMBER --cnum 100"
      - "-x FREQ  -y amp    -c ANTENNA1 --cnum 64"
      - "-x FREQ  -y real   -c CORR --corr IQUV --hline 0:"
      - "-x U     -y V      -c amp"
      - "-x U     -y V      -c phase --cmin -5 --cmax 5"
    plots:
      - "-x real  -y imag   -c SCAN_NUMBER --cnum 100 --col CORRECTED_DATA --iter-field"
      - "-x real  -y imag   -c ANTENNA1 --cnum 100 --col CORRECTED_DATA --iter-field"
      - "-x real  -y imag   -c SCAN_NUMBER --cnum 100 --col CORRECTED_DATA --iter-field --iter-corr"
      - "-x real  -y imag   -c ANTENNA1 --cnum 100 --col CORRECTED_DATA --iter-field --iter-corr"
      - "-x real  -y imag   -c SCAN_NUMBER --cnum 100 --col CORRECTED_DATA/MODEL_DATA --corr XX,YY --iter-field --iter-corr"
      - "-x real  -y imag   -c ANTENNA1 --cnum 100 --col CORRECTED_DATA/MODEL_DATA --corr XX,YY --iter-field --iter-corr"
      - '-x ANTENNA1 -y ANTENNA2 -a CORRECTED_DATA:amp --ared std --cmap pride --dir {msbase}-stdamp-byscan --iter-scan'
      - '-x ANTENNA1 -y ANTENNA2 -a CORRECTED_DATA:phase --ared std --cmap pride --dir {msbase}-stdphase-byscan --iter-scan'
      - '-x FREQ -y SCAN_NUMBER -a CORRECTED_DATA:amp --ared std --cmap pride --dir {msbase}-stdamp-byant --iter-ant'
      - '-x FREQ -y SCAN_NUMBER -a CORRECTED_DATA:phase --ared std --cmap pride --dir {msbase}-stdphase-byant --iter-ant'
      - '-x BASELINE_M -y FREQ --iter-scan -a CORRECTED_DATA:imag --ared std --amin 0 --amax 2 --cmap pride --dir {msbase}-stdimag-byscan'
 ```
Part of the problem with the above is that there's a lot of implicit structure and repetition in there, which dulls the mind when written out in such explicit terms. And, of course, you know what programmers like to do [when faced with structure and repetition](https://en.wikipedia.org/wiki/Turing_tarpit), right?

I think I have an entirely backwards-compatible solution to this though. Instead of ``plots`` being just a sequence of string plot specifiers, how about also allowing for a nested mapping. The mess above becomes something like:

```yml
    plots:
      - desc: "plots by field"
        field: "{all_fields}"
        cnum: 100  # up to 100 colours
        iter_field: 
        plots:
          # phaseball plots
          - dir: "phaseballs-{msbase}"
            plots:
              - "-x real -y imag -c CORR --corr IQUV --hline 0: --vline 0:"
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
          - dir: "phaseballs-bycorr-{msbase}"
            iter_corr:
            plots:
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
          # normalized phaseballs
          - dir: "normballs-{msbase}"
            col: "CORRECTED_DATA/MODEL_DATA"
            corr: "XX,YY"
            iter_corr:
            plots:
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
...
      # per-antenna plots
      - iter_ant:
        desc: "plots by antenna"
        cmap: pride
        corr: XX,YY
        plots:
          - '-x FREQ -y amp:I -c SCAN_NUMBER --cnum 100 --cmin 0 --cmax 30 --field {bpcal} --dir bpcal-iamp-byant-{msbase}'
          - '-x FREQ -y SCAN_NUMBER -a amp --ared std --dir stdamp-byant-{msbase}'
          - '-x FREQ -y SCAN_NUMBER -a phase --ared std --dir stdphase-byant-{msbase}'
```
...where keys in the mapping above specify plot parameters that are passed on to the lower levels. I find this a lot more readable and lucid, because the structure is now explicit in the yml file, while the plot specifiers themselves are minimal, and actually tell you what's being plotted. (Oh, and you can even disable an entire section by sticking an ``enable: false`` in there...)

This approach is completely backwards-compatible. A string in the ``plots`` sequence is parsed in the old way. The addition is that it will now also allow a mapping as a sequence element. The keys of the mapping are applied as extra arguments to the list of ``plots`` within the mapping. (This is endlessly nestable, and probably Turing-complete).

This can't be expressed in the schema file, so that just has a ``type: any`` entry to disable checking of the plots parameter. (However, the ``check_config`` function of the inspect worker will check the whole thing for correctness up front, which achieves the same result as the schema checking...)

Feedback solicited, but I should also mention this is already implemented on the ``add_polcal`` branch.
