### ISSUE TITLE
crosscal: apply_cal: applyto produces unexpected results when xcal is missing

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1323]
I had my config looking like this
```yml
crosscal:
  apply_cal: 
    applyto: 
      - gcal
      - bpcal
      - xcal
```
...but there was no xcal configured. The result was quite insidious: no errors, no complaints, but spiky looking phaseballs on the bpcal.

Upon investigation, it seems that the crosscal worker ran an extra step of applycal with ``field=""``, i.e. on all fields, using the default caltables (i.e. delay/phase derived from gcal). This is a no-op for gcal, but for the bpcal it results in degraded corrected data.

Correct behaviour when xcal is missing should be to ignore, or to throw an error.
