### ISSUE TITLE
Correlations in diagnostic plots 

### ISSUE THREAD

**Issue by ktrehaeven** [caracal-pipeline/caracal#1347]
I've found that the correlation option in the inspect worker overrides the shadeMS correlation option when writing freeform shadems plots. When `correlation: all` is specified, then all shadems plots are plotted with all correlations, despite specifying `--corr XX,YY` in the freeform shadems sequences.
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6668966/log-caracal.txt)
[log-inspect-plot-shadems-ms1-20210615-140224.txt](https://github.com/caracal-pipeline/caracal/files/6668967/log-inspect-plot-shadems-ms1-20210615-140224.txt)

**Comment by o-smirnov** [comment]
Yeah I guess I *could* check for a ``--corr`` argument and ignore the default correlation setting when this is specified. But in the meantime, there is a rather elegant workaround (at least on the ``add_polcal`` branch), which also lets you structure your free-form plots in a way that's easier to follow and maintain. Here's an example:

```yml
  shadems:
    enable: true
    default_column: CORRECTED_DATA
    plots:
      - desc: "plots by field"
        field: "{all_fields}"
        cnum: 100  # up 100 colours
        iter_field: true
        plots:
          # phaseball plots
          - dir: "phaseballs-{msbase}"
            plots:
              - "-x real -y imag -c CORR --corr IQUV --hline 0: --vline 0:"
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
          - dir: "phaseballs-bycorr-{msbase}"
            iter_corr:
            plots:
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
          # normalized phaseballs
          - dir: "normballs-{msbase}"
            col: "CORRECTED_DATA/MODEL_DATA"
            corr: "XX,YY"  ## <----- LOOK HERE! THIS OVERRIDES CORRELATIONS SET AT THE OUTER LEVEL
            iter_corr:
            plots:
              - "-x real -y imag -c SCAN_NUMBER"
              - "-x real -y imag -c ANTENNA1"
```
Note that every entry in the ``plots`` list can be string (i.e. a shadems command), but it can also be a nested mapping that specifies (a) some default shadems arguments, and (b) a nested ``plots`` list to which these default arguments apply. The nested list can also contain a mix of commands and nested sub-mappings... turtles all the way down.
