### ISSUE TITLE
Verbose syntax in line:subtractmodelcol line:addmodelcol

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#1367]
This 

https://github.com/caracal-pipeline/caracal/blob/8ae715fd24a21f6709d6380291a32b2e651f5857/caracal/schema/line_schema.yml#L63-L71

should be 

```yaml
      subtractmodelcol:
        desc: Replace the CORRECTED_DATA column of the .MS file(s) with the difference CORRECTED_DATA - MODEL_DATA. This is useful for continuum subtraction as it subtracts the continuum clean model written to MODEL_DATA. WARNING! The CORRECTED_DATA column is overwritten. To undo this operation enable the addmodelcol segment in this worker.
        type: bool
        required: false
        example: 'True'
```

something for `line:addmodelcol`
