### ISSUE TITLE
KeyError when using 'J1130-1449' as a polarization calibrator

### ISSUE THREAD

**Issue by Sinenhlanhla** [caracal-pipeline/caracal#1371]
I am trying to use 'J1130-1449', an unknown polcal source, to calibrate my data. After setting leakage_calib=pol_calib=xcal, I get this error:
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: ---------------------------------
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: Stimela version 1.7.0
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: Running: polcal
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: ---------------------------------
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: Config directory cannot be found. Will create /home/precious/merghers/.stimela_workdir-16321283915562663/stimela_parameter_files
2021-09-20 10:59:51 CARACal INFO: polcal: initializing
2021-09-20 10:59:51 CARACal INFO: RECEPTOR_ANGLE has been rotated by -90.0 degrees
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: Adding cab '/home/precious/stimela-images/stimela_casa_1.6.3.sif' (5.6.1-8) to recipe, container name 'save-cfp2020_4a_polcal_before-ms0'
2021-09-20 10:59:51 CARACal.Stimela.polcal INFO: Adding cab '/home/precious/stimela-images/stimela_casa_1.6.3.sif' (5.6.1-8) to recipe, container name 'extend_flags_polcal'
2021-09-20 10:59:51 CARACal INFO: You decided to calibrate the polarized angle and leakage with a polarized calibrator.
2021-09-20 10:59:51 CARACal INFO: Using a known model for the polarized calibrator.
2021-09-20 10:59:51 CARACal ERROR: 'J1130-1449' [KeyError]
2021-09-20 10:59:51 CARACal INFO:   More information can be found in the logfile at output/logs-20210920-105950/log-caracal.txt
2021-09-20 10:59:51 CARACal INFO:   You are running version 1.0.4
2021-09-20 10:59:51 CARACal ERROR: Traceback (most recent call last):
2021-09-20 10:59:51 CARACal ERROR:   File "/home/precious/venv/lib/python3.8/site-packages/caracal/main.py", line 183, in __run
2021-09-20 10:59:51 CARACal ERROR:     pipeline.run_workers()
2021-09-20 10:59:51 CARACal ERROR:   File "/home/precious/venv/lib/python3.8/site-packages/caracal/workers/worker_administrator.py", line 441, in run_workers
2021-09-20 10:59:51 CARACal ERROR:     worker.worker(self, recipe, config)
2021-09-20 10:59:51 CARACal ERROR:   File "/home/precious/venv/lib/python3.8/site-packages/caracal/workers/polcal_worker.py", line 1355, in worker
2021-09-20 10:59:51 CARACal
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/7194656/log-caracal.txt)
 ERROR:     xcal_model_xcal_leak(msname, msinfo, prefix_msbase, recipe, config, pipeline, i,
2021-09-20 10:59:51 CARACal ERROR:   File "/home/precious/venv/lib/python3.8/site-packages/caracal/workers/polcal_worker.py", line 410, in xcal_model_xcal_leak
2021-09-20 10:59:51 CARACal ERROR:     normfreq = (meanchanfreq / float(polarized_calibrators[field]["reffreq"][:-3]))
2021-09-20 10:59:51 CARACal ERROR: KeyError: 'J1130-1449'
2021-09-20 10:59:51 CARACal INFO: exiting with error code 1

**Comment by o-smirnov** [comment]
Use ``leakage_calib=bpcal``, and ``pol_calib=xcal``, and ask @francescaLoi to add J1130-1449 to the list of allowed polcals...

**Comment by o-smirnov** [comment]
ALso @Sinenhlanhla could you please post your .yml file so we can advise.

**Comment by o-smirnov** [comment]
And ``set_model_pol=false``.

**Comment by o-smirnov** [comment]
@bennahugo will give us a link to Bill Cotton's model for this calibrator, we'll add it.

**Comment by francescaLoi** [comment]
@Sinenhlanhla I just add a new branch with bandwidth averaged properties of J1130-1449. Could you please check if it works? The changes are in the **add_j1130** branch.
Remember to indicate J1130-1449 as your xcal calibrator in the obsconf worker. Then something like:
```
polcal:
  enable: true
  label_in: cal
  label_cal: 1pcal
  otfcal:
    enable: true
    label_cal: 1kgb
  extendflags: True
  feed_angle_rotation: '-90'
  uvrange: '>150'
  reuse_existing_tables: false
  pol_calib: xcal
  leakage_calib: fcal
  set_model_leakage:
    enable: true
    meerkat_skymodel: true
  set_model_pol: true
  gain_solint: '60s'
  time_solint: 'inf'
  plotgains: true
  apply_pcal: true
  applyto:
    - gcal
    - bpcal
    - xcal
```
should work.
