### ISSUE TITLE
Selfcal model transfer requires very large memory size

### ISSUE THREAD

**Issue by SpaceMeerkat** [caracal-pipeline/caracal#1434]
## Description of issue

I'm attempting to perform a selfcal model transfer, but cubical is saying that the total estimated memory usage is ~600 Gig (see error message below). 

This is for a 32K MeerKAT observation using 3905 channels, but during the selfcal modelling I'm channel averaging with 100 channels per bin in the hopes of using less memory and keeping the compute speed as high as possible. With that in mind, is ~600 Gig an overly large memory estimate or is this regular for the number of channels involved?

I see that in the error message below there are some suggestions as to how to reduce the memory by 'lowering the number of chunks, the dimensions of each chunk or the number of worker processes'. However this is my first time reducing 32K data so I'm wondering if there's perhaps some clear step in my config script that is far too bloated for 32K data but has so far been fine for 4K data? I'll put my current selfcal config file below in case that is useful in this regard.

Many thanks in advance for any help in this matter! 

---

**The error report:**

> INFO      20:45:18 - data_handler       [0.9 8.0 0.0Gb]   generated 170 row chunks based on time and DDID
> INFO      20:45:18 - data_handler       [0.9 8.0 0.0Gb]   row chunks yield 170 potential tiles
> INFO      20:45:18 - data_handler       [0.9 8.0 0.0Gb]   coarsening this to 22 tiles (max 8 chunks per tile, based on 31.0/8 requested)
> INFO      20:45:18 - main               [0.9 8.0 0.0Gb] multi-process mode: 8+1 workers, single thread
> INFO      20:45:18 - wisdom             [0.9 8.0 0.0Gb] Detected a total of 236.16GiB of system memory.
> INFO      20:45:18 - wisdom             [0.9 8.0 0.0Gb] Per-solver (worker) memory use estimated at 55.85GiB: 23.65% of total system memory.
> INFO      20:45:18 - wisdom             [0.9 8.0 0.0Gb] Peak I/O memory use estimated at 160.87GiB: 68.12% of total system memory.
> INFO      20:45:18 - wisdom             [0.9 8.0 0.0Gb] Total peak memory usage estimated at **607.71GiB: 257.34% of total system** memory.
> INFO      20:45:18 - main               [0.9 8.0 0.0Gb] Exiting with exception: MemoryError(Estimated memory usage exceeds allowed pecentage of system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by setting --dist-safe to zero.)
>  Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 548, in main
>     estimate_mem(ms, tile_list, GD["data"], GD["dist"])
>   File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/wisdom.py", line 90, in estimate_mem
>     "Estimated memory usage exceeds allowed pecentage of system "
> MemoryError: Estimated memory usage exceeds allowed pecentage of system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by setting --dist-safe to zero.

---

**The selfcal config script**

```
schema_version: 1.0.3

general:
  prefix: caracal
  msdir: '/scratch3/users/anonymous/32K/msdir'
  input: '/scratch3/users/anonymous/32K/input'
  output: '/scratch3/users/anonymous/32K/output'

getdata:
  dataid: ['1645290976_sub']
  extension: ms


obsconf:
  refant: 'auto'

transform__avg:
  enable: false
  label_in: corr
  label_out: corrfreqavg
  split_field:
    enable: true
    chan_avg: 100
    col: 'all'
    otfcal:
      enable: false
      label_cal: 1gc1

selfcal:
  enable: false
  label_in: corrfreqavg
  img_npix: 3600
  img_cell: 2
  ncpu: 32
  img_nchans: 4
  img_specfit_nrcoeff: 3
  img_robust: -0.5
  img_nrdeconvsubimg: 8
  cal_niter: 2
  cal_gain_cliplow: 0
  cal_gain_cliphigh: 0
  cal_cubical:
    max_prior_error: 0
    max_post_error: 0
    flag_madmax: false
    shared_mem: 220Gb
    dist_max_chunks: 8
  image:
    enable: true
    clean_cutoff: [0.5,]
    cleanmask_method: [sofia,] 
    cleanmask_thr: [4.5,5.,6.]
    cleanmask_localrms: [True,]
    cleanmask_localrms_window: [100,]
  img_sofia_settings:
    kernels: [0, 3, 6, 12, 24]
  calibrate:
    enable: true
    gain_matrix_type: [GainDiagPhase,]
    gsols_timeslots: [15,]
  transfer_apply_gains:
    enable: false
    transfer_to_label: corr
    interpolate:
      enable: true
  transfer_model:
    enable: false
    transfer_to_label: corr

selfcal__transfer:
  enable: true
  label_in: corrfreqavg
  img_npix: 3600
  img_cell: 2
  ncpu: 32
  img_nchans: 4
  img_specfit_nrcoeff: 3
  img_robust: -0.5
  img_nrdeconvsubimg: 8
  cal_niter: 2
  cal_gain_cliplow: 0
  cal_gain_cliphigh: 0
  cal_cubical:
    max_prior_error: 0
    max_post_error: 0
    flag_madmax: false
    shared_mem: 220Gb
    dist_max_chunks: 8
  image:
    enable: false
  calibrate:
    enable: false
    gain_matrix_type: [GainDiagPhase,]
    gsols_timeslots: [15,]
  transfer_apply_gains:
    enable: true
    transfer_to_label: corr
    interpolate:
      enable: true
  transfer_model:
    enable: true
    transfer_to_label: corr
```
