### ISSUE TITLE
Still facing the exact same 'Flag summary error'

### ISSUE THREAD

**Issue by rramij** [caracal-pipeline/caracal#1463]
Facing the exact same 'Flag summary error' in [#1422](https://github.com/caracal-pipeline/caracal/issues/1422) 
Then added the antennas as follows:

```
transform:
  enable: true
  label_out: cal
  field: calibrators
  split_field:
    enable: true
    col: data
    antennas: 'C00,C01,C02,C03,C04,C05,C06,C08,C09,C10,C11,C12,C13,C14,E02,E03,E04,E05,E06,S01,S02,S03,S04,S06,W01,W02,W03,W04,W05,W06&'
```

Now the pipeline stops running. Returning below error:

````
2022-12-23` 15:23:12 CARACal INFO: Invoked as /home/rramij/venv/bin/caracal -ct singularity -c uGMRT_pipe.yml -sid /home/rramij/singularity_images
2022-12-23 15:23:13 CARACal ERROR: configuration file uGMRT_pipe.yml fails to validate, list of errors follows:
  transform:
    - Key 'antennas' was not defined. Path: '/transform/split_field'
``
```

_Originally posted by @rramij in https://github.com/caracal-pipeline/caracal/issues/1422#issuecomment-1363962347_
