### ISSUE TITLE
Velocities after primary beam correction look strange

### ISSUE THREAD

**Issue by SpaceMeerkat** [caracal-pipeline/caracal#1470]
Perhaps related to closed issue: https://github.com/caracal-pipeline/caracal/issues/1230#issue-688516338

After running primary beam correction in the line worker..

```
    ...
  make_cube:
    enable: true
    npix: [1200]
    cell: 6
    robust: 0.5
    taper: 20
    niter: 1000000
    wscl_mgain: 1
    wscl_nrdeconvsubimg: 1
    wscl_sofia_niter: 3
  pb_cube:
    enable: true
    apply_pb: true
  remove_stokes_axis:
    enable: true
  freq_to_vel:
    enable: true 
  report: true
```

... the velocities in the resulting corrected cube are looking far too large. (Pre `apply_pb`: 32000 to -22000 km/s, after pb_corr: 299788.6497 to 299787.8834 km/s for my current MeerKAT cube).

Is this an artefact of the `pb_cube` vs `freq_to_vel` ordering still? And can it be easily undone by rerunning the line worker in a different way?

Many thanks!
