### ISSUE TITLE
Need input mask option for ddcal

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/caracal#1496]
I have a 2Jy source on the edge of my fields that really needs direction dependent calibration. The parameters I have been using:
```
  image_dd:
    enable: true
    npix: 5800
    cell: 2
    facets_nfacets: 18
    weight_robust: -0.5
    deconv_maxminoriter: 50000
    parallel_ncpu: 29
  calibrate_dd:
    enable: true
    de_sources_mode: manual
    de_target_manual: ['Bhairavi']
    de_sources_manual: ['23h40m23.181s, 22d20m54.02s, 10.0']
```

I have left all the masking parameters as the default, but even with a 10sigma clip, the automasking is including the sidelobes of all the bright sources in the model which defeats the purpose. I attach a screenshot of the brightest source to illustrate the issue:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/11073757/230577398-b7403e22-f974-43cf-bd58-7843ff18400a.png">

Ideally here I would provide a user input mask which would also help reduce compute time.
