### ISSUE TITLE
transform worker with otfcal fails with vague error message when MS contains a period other than ".ms"

### ISSUE THREAD

**Issue by ErikOsinga** [caracal-pipeline/caracal#1634]
When applying cross-cal and polcal solutions using the following transform parset

```
transform__2:
  enable: true
  label_out: corr
  field: target
  split_field:
    enable: true
    col: corrected
    nthreads: 8
    time_avg: '16s'
    chan_avg: 10
    otfcal:
      enable: true
      label_cal: 1kgb
      label_pcal: 1pcal
```

I was getting the vague error

```
# 2025-05-21 03:34:55	SEVERE	OldCalibrater::setcallib2(callib)	Field mapping by selection failure:  matches no fields. Check inputs and try again.
```

which (after a lot of digging) turned out to be because the `callib` file that was written was being overwritten due to the `label_cal` and `label_pcal` dropping off, because my measurement set contained multiple `.` like .e.g `coma_mosaic1.try1.ms`

from the logs:

```
2025-05-22 20:14:16 CARACal INFO: applying OTF cross-cal from callib-caracalpipelinerun-coma_mosaic1-transform__2.txt
2025-05-22 20:14:16 CARACal INFO: applying OTF polcal from callib-caracalpipelinerun-coma_mosaic1-transform__2.txt
```

which should have been files named like `coma_mosaic1.try1-**1kgb**-transform__2.txt` and `coma_mosaic1.try1-**1pcal**-transform__2.txt` but I found that this line

https://github.com/caracal-pipeline/caracal/blob/eaea8656488664bb54323706534c23154c200d63/caracal/workers/worker_administrator.py#L246

is splitting off the "extension" off of the `cal_lib`, 

https://github.com/caracal-pipeline/caracal/blob/eaea8656488664bb54323706534c23154c200d63/caracal/workers/utils/callibs.py#L94

which in this case (always?) already doesn't contain `.ms` any more, so I'm unsure why we would split off the extension.

This was quite a headache to figure out, and maybe only affected me because I tend to name MSes with multiple `.` in the filenames while maybe I shouldn't, but if caracal is that sensitive to this, maybe a check to confirm the input MS (`dataid`) doesn't contain any `.` would prevent this.
