### ISSUE TITLE
Error Mosaicking  MeerKAT HI CUBES

### ISSUE THREAD

**Issue by bnamumba** [caracal-pipeline/caracal#1637]
I have multiple pointings from the MeerKAT data, and I’m encountering the following error when trying to combine the cubes.
# 2025-06-04 10:49:49,313 - MAKE_MOSAIC - INFO - Mosaicking ...
# Traceback (most recent call last):
#   File "/usr/local/bin/MosaicSteward", line 8, in <module>
#     main.main(sys.argv[1:])
#   File "/usr/local/lib/python3.6/dist-packages/MosaicSteward/main.py", line 92, in main
#     make_mosaic.make_mosaic_using_beam_info(input_dir, output_dir, mosaic_type, outname, imagesR, beamsR, cutoff, images)
#   File "/usr/local/lib/python3.6/dist-packages/MosaicSteward/make_mosaic.py", line 145, in make_mosaic_using_beam_info
#     mos_array = np.zeros((int(moshead['NAXIS3']), int(
# KeyError: 'NAXIS3'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 49, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['MosaicSteward', '--mosaic-type', 'spectral', '--domontage', '--cutoff', '0.2', '--name', 'mosaic', '--input', '/stimela_mount/input/output/cubes', '--target-images', 'WLM_WLM5_taper50_robust05.image.fits', '--target-images', 'WLM_WLM6_taper50_robust05.image.fits', '--output', '/stimela_mount/output']' returned non-zero exit status 1

[log-caracal.txt](https://github.com/user-attachments/files/20607703/log-caracal.txt)

**Comment by paoloserra** [comment]
Can you check https://caracal.readthedocs.io/en/latest/manual/workers/mosaic/index.html#round-cdelt3 ?

Basically, if there are small differences in CDELT3 the code will crash. You can use that parameter to get around that issue.

**Comment by bnamumba** [comment]
Hi Paolo,
Aside from the CDELT3 issue, I noticed that the process generates a .hdr file with 2D information instead of 3D, which causes the mosaic to fail. I had to manually edit the .hdr file to make it 3D, then re-run the process, and it worked.

**Comment by bnamumba** [comment]
So even after setting round_cdelt3: 2 still gives me  .hdr  with 2D information. Unless I manually edit the .hdr to 3D.

**Comment by paoloserra** [comment]
Do you mind sending the full log of the latest run and, if possible, the values of CDELT3 in the input cubes? Thanks!

**Comment by bnamumba** [comment]
WLM_WLM1_taper50_robust05.image.fits: CDELT3 = -689.13
WLM_WLM0_taper50_robust05.pb.fits: CDELT3 = -689.13
WLM_WLM1_taper50_robust05.pb.fits: CDELT3 = -689.13
WLM_WLM0_taper50_robust05.image.fits: CDELT3 = -689.13

```

.yml
general:
  title: GPS
  rawdatadir: ''
  msdir: msdir
  input: input
  output: output
  prefix: ''  # !!! rename for each data set 
  final_report: false

getdata:
  dataid: ['wlm_final1']  # !!! rename for each data set, without extention # empty file
  ignore_missing: true #false  

mosaic:
  enable: true
  mosaic_type: spectral #continuum # spectral
  target_images:
    - cubes/WLM_WLM0_taper50_robust05.image.fits
    - cubes/WLM_WLM1_taper50_robust05.image.fits
  label_in: ''
  line_name: HI
  use_mfs: false #true
  name: 'mosaic' #The prefix to be used for output files.
  domontage: # Re-grid the input images, and associated beams.
    enable: true  # false # test1
  cutoff: 0.2
  pb_type: mauchian
  dish_diameter: 13.5
  round_cdelt3: 0 #do not round
  ref_frequency: 1368847656.250 # 1383685546.875
  report: false
```
output mosaic.hdr 

```
SIMPLE  = T
BITPIX  = -64
NAXIS   = 2
NAXIS1  = 1306
NAXIS2  = 1482
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
EQUINOX = 2000
CRVAL1  =    0.269606678
CRVAL2  =  -15.566132164
CRPIX1  =       653.5000
CRPIX2  =       741.5000
CDELT1  =   -0.001666667
CDELT2  =    0.001666667
CROTA2  =  359.978048095
END
```                                                             

[log-caracal.txt](https://github.com/user-attachments/files/20678133/log-caracal.txt)
