### ISSUE TITLE
Default config file: Fixes needed

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#280]
I am trying to use Meerkathi in an end-to-end mode (which is after all, **the** objective). For this we need to change some of the default configuration which is there currently.

The self cal section in particular:
```
  calibrate:
    enable: true
    model: ['1', '2', '2+3', '2+3']
    output_data: CORR_DATA
    gain_matrix_type: GainDiagPhase
    add_vis_model: true 
  restore_model: 
    enable: true
    model: '2+3'
    clean_model: '4'
```
This is only correct if the _output_data_ parameter is _CORR_RES_. What happens currently is that the final model has multiple copies of the same sources in it. Since there is only Phase calibration happening, this doesn't show up very drastically. The latter is again another point of contention - we should be able to do both amplitude and phase calibration - I don't know if there is a point in doing four rounds of phase self cal?
Again, the clean component calibration adds the same sources back in calibration, so to speak. 

These are rather trivial changes, but can make large differences, especially for new users.
