### ISSUE TITLE
"eidos: not found" when trying to generate primary beam

### ISSUE THREAD

**Issue by svw26** [caracal-pipeline/caracal#562]
Hiya,

I am running the short config file below, over the test dataset 1477074305.subset.ms
```
!!omap
- schema_version: 0.1.0

- general:
    data_path: input/data
    msdir: msdir
    input: input
    output: output
    prefix: meerkathi-pipeline
    init_pipeline: true

- get_data:
    dataid: ['1477074305.subset']
    mvftoms:
      enable: false
      channel_range: 'null'
    untar:
      enable: false
    combine:
      enable: false

- observation_config:
    obsinfo:
      enable: true
    bpcal: auto
    fcal: auto
    gcal: auto
    xcal: auto
    target: auto
    reference_antenna: '0'
    primary_beam:
      enable: true
```

It complains that "eidos: not found", as shown in log-primary_beam.txt : 
```
-----------------------------------
Stimela version     : 1.0.1
Cab name            : stimela/eidos:1.1.1
-------------------------------------

-----------------------------------
Stimela version     : 1.0.1
Cab name            : stimela/eidos:1.1.1
-------------------------------------
Running: eidos --pixels 256 --freq 855 1760 64 --diameter 6.0 --coefficients-file /scratch/input/meerkat_coeff_dict.npy --prefix /scratch/output/meerkathi-pipeline --output-eight 
/bin/sh: 1: eidos: not found

Traceback (most recent call last):
  File "/scratch/code/run.py", line 28, in <module>
    utils.xrun(cab['binary'], args)
  File "/scratch/stimela/utils/__init__.py", line 111, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
utils.StimelaCabRuntimeError: eidos: returns errr code 127

-----------------------------------
Stimela version     : 1.0.1
Cab name            : stimela/eidos:1.1.1
-------------------------------------
Running: eidos --pixels 256 --freq 855 1760 64 --diameter 6.0 --coefficients-file /scratch/input/meerkat_coeff_dict.npy --prefix /scratch/output/meerkathi-pipeline --output-eight 
/bin/sh: 1: eidos: not found

Traceback (most recent call last):
  File "/scratch/code/run.py", line 28, in <module>
    utils.xrun(cab['binary'], args)
  File "/scratch/stimela/utils/__init__.py", line 111, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
utils.StimelaCabRuntimeError: eidos: returns errr code 127
```

This could be connected to the issue I raised in the stimela repository, where eidos was not automatically downloaded via 'stimela pull'?

Note that the default config file has "- observation_config: primary_beam: enable: false", so this aspect may not have been tested for a while.

Thanks,
Sarah x
