### ISSUE TITLE
Dealing with multiple target fields

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#69]
TO DO:
- Auto select which fields need to be imaged together based on the pointing direction
- Allow manual mode, where the user can specify which fields (across datasets) they want to image together. 

The target specification should look something like this

```
target: 
  im1: 
    ms1: field1,field2,field3
    ms2: field1,field2
 im2:
   ms1: field4,field5,field6
   ms2: field3,field4,field5
```

Then make multiple images, e.g., the first image is made of  datasets 1 and 2, and images fields 1,2,3 and 1,2 in those datasets resp.

- Add montage to create mosiacs 

We then have to change the behaviour of the *split_target*, and *self_cal* workers
